=== 15600800736/H-flex/src/main/resources/frame-haug.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT frame-haug (annotation-scan?,action-classes?,actions?)>

<!ELEMENT action-classes (action-class|base-contents)>
<!ELEMENT action-class (path+)>
<!ATTLIST action-class class-name CDATA #REQUIRED>
<!ELEMENT path (#PCDATA)>

<!ELEMENT base-contents (path+)>
<!ELEMENT annotation-scan EMPTY>

<!ELEMENT actions (action+)>
<!ELEMENT action (#PCDATA)>

<!ATTLIST action action-path CDATA #REQUIRED>
<!ATTLIST action action-alias CDATA #IMPLIED>

=== 15600800736/H-flex/src/main/resources/test.xml
<!DOCTYPE frame-haug SYSTEM "frame-haug.dtd">

<frame-haug>
    <annotation-scan/>
    <action-classes>
        <action-class class-name="">
            <path></path>
        </action-class>
    </action-classes>

    <actions>
        <action action-path=""></action>
        <action action-path=""></action>
        <action action-path="" action-alias=""></action>
    </actions>


</frame-haug>
